spring:
  application:
    name: application.name=hexagonal
  data:
    mongodb:
      uri: mongodb://localhost:27017/hexagonal

server:
  port: 8081

ribeiro:
  client:
    address:
      url: http://localhost:8082/addresses
